---

- hosts: backend
  become: yes

  tasks:
    - name: Start Flask backend
      shell: nohup /home/ubuntu/to-do-app/backend/venv/bin/python app.py > backend.log 2>&1 &
      args:
        chdir: /home/ubuntu/to-do-app/backend