---
- hosts: backend
  become: yes

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install prerequisites
      apt:
        name:
          - curl
          - python3
          - python3-venv
        state: present
        update_cache: yes

    - name: Clone repository
      git:
        repo: 'https://github.com/prakashmtiwari/terraform-ansible-to-do-app.git'
        dest: /home/ubuntu/to-do-app
        version: main

    - name: Create virtual environment
      command: python3 -m venv /home/ubuntu/to-do-app/backend/venv
      args:
         creates: /home/ubuntu/to-do-app/backend/venv

    - name: Install backend dependencies
      command: /home/ubuntu/to-do-app/backend/venv/bin/pip install -r requirements.txt
      args:
        chdir: /home/ubuntu/to-do-app/backend
